export type Film = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  numberOfParts: number | null;
  totalTime: number | null;
  title: string | null;
  archiveNumber: string | null;
  releaseYear: number | null;
  studio: string | null;
  screenwriter: string | null;
  sound: string | null;
  color: string | null;
  format: string | null;
  carrier: string | null;
  director: string | null;
  cinematographer: string | null;
  otherParticipants: string | null;
  annotation: string | null;
};
